spring:
  datasource:
    username: postgres
    password: smndr2013
    url: jdbc:postgresql://localhost:5432/anor_chat
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080