export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const GET_CHATS = "GET_CHATS"
export const GET_CHAT = "GET_CHAT"